[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  ZOHO_MAIL_FROM = "ventas@norwestds.com"
  ZOHO_MAIL_TO = "ventas@norwestds.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200