#!/usr/bin/env python3
"""
Blender script — imports an STL file and renders an isometric PNG preview.

Called by worker.py as:
  blender --background --python blender_render.py -- <input.step> <output.png>

Looks for <input.stl> (generated by freecad_gen.py) for native import.
Tries Blender 4.x operator (wm.stl_import) then 3.x (import_mesh.stl).
Uses CYCLES CPU for reliable headless rendering (no GPU needed).
"""

import sys
from pathlib import Path


def parse_args():
    argv = sys.argv
    sep = argv.index('--') if '--' in argv else len(argv)
    args = argv[sep + 1:]
    if len(args) < 2:
        print('Usage: blender_render.py -- input.step output.png')
        sys.exit(1)
    return Path(args[0]), Path(args[1])


def import_geometry(input_step):
    import bpy

    stl_file = input_step.with_suffix('.stl')

    if stl_file.exists():
        # Blender 4.x built-in importer
        try:
            bpy.ops.wm.stl_import(filepath=str(stl_file))
            print(f'[blender_render] imported STL (wm.stl_import): {stl_file}', flush=True)
            return
        except AttributeError:
            pass
        # Blender 3.x addon importer
        try:
            bpy.ops.import_mesh.stl(filepath=str(stl_file))
            print(f'[blender_render] imported STL (import_mesh.stl): {stl_file}', flush=True)
            return
        except AttributeError:
            pass

    # STEP fallback (needs CAD add-on)
    try:
        bpy.ops.import_scene.step(filepath=str(input_step))
        print(f'[blender_render] imported STEP: {input_step}', flush=True)
        return
    except AttributeError:
        pass

    bpy.ops.mesh.primitive_cube_add(size=2)
    print('[blender_render] WARNING: no importer available — cube placeholder', flush=True)


def scene_bounds(meshes):
    """Return (cx, cy, cz, bb_l, bb_w, bb_h) from all mesh bounding boxes."""
    import mathutils
    corners = []
    for o in meshes:
        for v in o.bound_box:
            corners.append(o.matrix_world @ mathutils.Vector(v))
    if not corners:
        return 0.0, 0.0, 0.0, 2.0, 2.0, 2.0
    xs = [c.x for c in corners]
    ys = [c.y for c in corners]
    zs = [c.z for c in corners]
    bb_l = max(xs) - min(xs)
    bb_w = max(ys) - min(ys)
    bb_h = max(zs) - min(zs)
    cx = (min(xs) + max(xs)) / 2
    cy = (min(ys) + max(ys)) / 2
    cz = (min(zs) + max(zs)) / 2
    return cx, cy, cz, max(bb_l, 0.1), max(bb_w, 0.1), max(bb_h, 0.1)


def render_with_blender(input_step, output_png):
    import bpy
    import mathutils

    bpy.ops.wm.read_factory_settings(use_empty=True)

    import_geometry(input_step)

    meshes = [o for o in bpy.context.scene.objects if o.type == 'MESH']

    # Apply material
    if meshes:
        mat = bpy.data.materials.new(name='Structure')
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get('Principled BSDF')
        if bsdf:
            bsdf.inputs['Base Color'].default_value = (0.55, 0.65, 0.75, 1.0)
            bsdf.inputs['Metallic'].default_value = 0.6
            bsdf.inputs['Roughness'].default_value = 0.35
        for o in meshes:
            if o.data.materials:
                o.data.materials[0] = mat
            else:
                o.data.materials.append(mat)

    import math
    cx, cy, cz, bb_l, bb_w, bb_h = scene_bounds(meshes)

    # 3D diagonal guarantees the full isometric projection fits regardless of
    # which dimension dominates — single-axis extent is not enough.
    diag3 = math.sqrt(bb_l**2 + bb_w**2 + bb_h**2)
    dist  = diag3 * 0.8

    # ortho_scale: isometric projection of (L+W) base + full height, 20% margin
    proj_base = (bb_l + bb_w) / math.sqrt(2)
    proj_vert = bb_h + proj_base * 0.5
    # For 4:3 render, scale must satisfy both width and height
    ortho_scale = max(proj_base, proj_vert / 0.75) * 1.25

    # Aim slightly above centre so the full height of the frame is used
    target = mathutils.Vector((cx, cy, cz + bb_h * 0.15))

    cam_data = bpy.data.cameras.new('Camera')
    cam_data.type = 'ORTHO'
    cam_data.ortho_scale = ortho_scale
    cam_data.clip_start = diag3 * 0.0001
    cam_data.clip_end   = diag3 * 20
    cam_obj = bpy.data.objects.new('Camera', cam_data)
    bpy.context.collection.objects.link(cam_obj)
    cam_obj.location = mathutils.Vector((cx + dist, cy - dist, cz + dist))
    cam_obj.rotation_euler = (target - cam_obj.location).to_track_quat('-Z', 'Y').to_euler()
    bpy.context.scene.camera = cam_obj

    # Sun lights (work well with CYCLES CPU)
    def add_sun(dx, dy, dz, energy):
        bpy.ops.object.light_add(type='SUN', location=(0, 0, 0))
        sun = bpy.context.active_object
        sun.data.energy = energy
        sun.rotation_euler = mathutils.Vector((dx, dy, dz)).to_track_quat('-Z', 'Y').to_euler()

    add_sun(-1, -0.5, -1, 3.0)
    add_sun(1,  0.5, -0.5, 1.5)
    add_sun(0.2, 1.0, -1, 0.8)

    # Light gray world
    scene = bpy.context.scene
    world = bpy.data.worlds.new('World')
    world.use_nodes = True
    bg = world.node_tree.nodes.get('Background')
    if bg:
        bg.inputs['Color'].default_value = (0.85, 0.85, 0.85, 1.0)
        bg.inputs['Strength'].default_value = 0.5
    scene.world = world

    # CYCLES CPU — reliable headless, no GPU needed
    scene.render.engine = 'CYCLES'
    scene.cycles.device = 'CPU'
    scene.cycles.samples = 64
    scene.cycles.use_denoising = True

    scene.render.resolution_x = 1280
    scene.render.resolution_y = 960
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = 'PNG'
    scene.render.image_settings.color_mode = 'RGB'
    scene.render.film_transparent = False
    scene.render.filepath = str(output_png)

    bpy.ops.render.render(write_still=True)
    print(f'[blender_render] PNG rendered: {output_png} ({output_png.stat().st_size} bytes)', flush=True)


def write_stub_png(output_png):
    import struct, zlib

    def chunk(tag, data):
        raw = tag + data
        return struct.pack('>I', len(data)) + raw + struct.pack('>I', zlib.crc32(raw) & 0xFFFFFFFF)

    ihdr = chunk(b'IHDR', struct.pack('>IIBBBBB', 1, 1, 8, 2, 0, 0, 0))
    idat = chunk(b'IDAT', zlib.compress(b'\x00\x80\x80\x80'))
    iend = chunk(b'IEND', b'')
    output_png.write_bytes(b'\x89PNG\r\n\x1a\n' + ihdr + idat + iend)
    print('[blender_render] stub PNG written (Blender not available)', flush=True)


def main():
    input_step, output_png = parse_args()

    try:
        render_with_blender(input_step, output_png)
    except ImportError:
        write_stub_png(output_png)
    except Exception as e:
        print(f'[blender_render] render error: {e}', flush=True)
        import traceback
        traceback.print_exc()
        write_stub_png(output_png)


if __name__ == '__main__':
    main()
