#!/usr/bin/env python3
"""
Blender script — imports a STEP/STL file and renders an isometric PNG preview.

Called by worker.py as:
  blender --background --python blender_render.py -- <input.step> <output.png>

Prefers <input.stl> (generated by freecad_gen.py) for native import.
Uses CYCLES CPU so the render works reliably in headless Docker (no GPU needed).
Falls back to a minimal stub PNG when Blender is not available.
"""

import sys
from pathlib import Path


def parse_args():
    argv = sys.argv
    sep = argv.index('--') if '--' in argv else len(argv)
    args = argv[sep + 1:]
    if len(args) < 2:
        print('Usage: blender_render.py -- input.step output.png')
        sys.exit(1)
    return Path(args[0]), Path(args[1])


def render_with_blender(input_step, output_png):
    import bpy
    import mathutils

    bpy.ops.wm.read_factory_settings(use_empty=True)

    # Prefer STL (native Blender import, no add-on); fall back to STEP CAD add-on
    stl_file = input_step.with_suffix('.stl')
    if stl_file.exists():
        bpy.ops.import_mesh.stl(filepath=str(stl_file))
        print(f'[blender_render] imported STL: {stl_file}', flush=True)
    else:
        try:
            bpy.ops.import_scene.step(filepath=str(input_step))
            print(f'[blender_render] imported STEP: {input_step}', flush=True)
        except AttributeError:
            bpy.ops.mesh.primitive_cube_add(size=2)
            print('[blender_render] WARNING: no STL/STEP import available — using cube placeholder', flush=True)

    # Fit camera to imported geometry
    meshes = [o for o in bpy.context.scene.objects if o.type == 'MESH']
    if meshes:
        mat = bpy.data.materials.new(name='Structure')
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get('Principled BSDF')
        if bsdf:
            bsdf.inputs['Base Color'].default_value = (0.55, 0.65, 0.75, 1.0)
            bsdf.inputs['Metallic'].default_value = 0.6
            bsdf.inputs['Roughness'].default_value = 0.35
        for o in meshes:
            o.select_set(True)
            if o.data.materials:
                o.data.materials[0] = mat
            else:
                o.data.materials.append(mat)

        # Centre of bounding box
        mins = [min(o.matrix_world @ mathutils.Vector(v) for v in [
            mathutils.Vector(o.bound_box[i]) for i in range(8)
        ])[axis] for axis in range(3)]
        maxs = [max((o.matrix_world @ mathutils.Vector(o.bound_box[i]))[axis]
                    for o in meshes for i in range(8)) for axis in range(3)]
        cx = (mins[0] + maxs[0]) / 2
        cy = (mins[1] + maxs[1]) / 2
        cz = (mins[2] + maxs[2]) / 2
        radius = max(maxs[i] - mins[i] for i in range(3)) * 0.75 + 0.5

        cam_loc = mathutils.Vector((cx + radius, cy - radius, cz + radius))
        target  = mathutils.Vector((cx, cy, cz))
    else:
        cam_loc = mathutils.Vector((4, -4, 4))
        target  = mathutils.Vector((0, 0, 0))
        radius  = 4.0

    # Orthographic isometric camera
    cam_data = bpy.data.cameras.new('Camera')
    cam_data.type = 'ORTHO'
    cam_data.ortho_scale = radius * 2.5
    cam_obj = bpy.data.objects.new('Camera', cam_data)
    bpy.context.collection.objects.link(cam_obj)
    cam_obj.location = cam_loc
    direction = target - cam_loc
    rot_quat = direction.to_track_quat('-Z', 'Y')
    cam_obj.rotation_euler = rot_quat.to_euler()
    bpy.context.scene.camera = cam_obj

    # Three-point lighting (Sun lamps work well with CYCLES CPU)
    def add_sun(direction_vec, energy, name):
        bpy.ops.object.light_add(type='SUN', location=(0, 0, 0))
        sun = bpy.context.active_object
        sun.name = name
        sun.data.energy = energy
        rot = mathutils.Vector(direction_vec).to_track_quat('-Z', 'Y')
        sun.rotation_euler = rot.to_euler()

    add_sun((-1, -0.5, -1), 3.0, 'KeyLight')
    add_sun((1,  0.5, -0.5), 1.5, 'FillLight')
    add_sun((0.2, 1.0, -1), 0.8, 'RimLight')

    # Light gray world background
    scene = bpy.context.scene
    world = bpy.data.worlds.new('World')
    world.use_nodes = True
    bg_node = world.node_tree.nodes.get('Background')
    if bg_node:
        bg_node.inputs['Color'].default_value = (0.9, 0.9, 0.9, 1.0)
        bg_node.inputs['Strength'].default_value = 0.6
    scene.world = world

    # CYCLES CPU — reliable in headless Docker (no GPU/OpenGL required)
    scene.render.engine = 'CYCLES'
    scene.cycles.device = 'CPU'
    scene.cycles.samples = 64
    scene.cycles.use_denoising = True

    scene.render.resolution_x = 1280
    scene.render.resolution_y = 960
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = 'PNG'
    scene.render.image_settings.color_mode = 'RGBA'
    scene.render.film_transparent = False
    scene.render.filepath = str(output_png)

    bpy.ops.render.render(write_still=True)
    print(f'[blender_render] PNG rendered: {output_png} ({output_png.stat().st_size} bytes)', flush=True)


def write_stub_png(output_png):
    """Write the smallest valid PNG (1x1 gray pixel) as fallback."""
    import struct
    import zlib

    def chunk(tag, data):
        raw = tag + data
        return struct.pack('>I', len(data)) + raw + struct.pack('>I', zlib.crc32(raw) & 0xFFFFFFFF)

    ihdr = chunk(b'IHDR', struct.pack('>IIBBBBB', 1, 1, 8, 2, 0, 0, 0))
    idat = chunk(b'IDAT', zlib.compress(b'\x00\x80\x80\x80'))
    iend = chunk(b'IEND', b'')
    output_png.write_bytes(b'\x89PNG\r\n\x1a\n' + ihdr + idat + iend)
    print('[blender_render] stub PNG written (Blender not available)', flush=True)


def main():
    input_step, output_png = parse_args()

    try:
        render_with_blender(input_step, output_png)
    except ImportError:
        write_stub_png(output_png)
    except Exception as e:
        print(f'[blender_render] render error: {e}', flush=True)
        write_stub_png(output_png)


if __name__ == '__main__':
    main()
